services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    ports:
      - '5432:5432'
    volumes:
      - postgres-data-cw:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis_container-cw
    environment:
      - REDIS_PASSWORD=redispassword
    ports:
      - "6381:6379"
    volumes:
      - redis-data-cw:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "redispassword", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
volumes:
  postgres-data-cw:
  redis-data-cw: