spring:
  data:
    redis:
      port: 6381
      host: localhost
      password: redispassword
      username: redisuser
      userpassword: redisuserpassword
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: secret
server:
  servlet:
    context-path: /api

backup:
  directory: /Users/ivanberezuckij/university/db/coursework/backups
  dbName: mydb